### ISSUE TITLE
Migrate to hugo

### ISSUE THREAD

**Issue by IRus** [KotlinBy/bkug.by#2]

**Comment by madhead** [comment]
А где глянуть текущий вордпресовский сайтец? Я бы помог с Hugo.

**Comment by IRus** [comment]
https://github.com/BenSibley/Author Вот эта тема юзается, а так - вордпресс-вордпрессом. Могу дать доступ в админку

**Comment by madhead** [comment]
Слить бы пару статей, чтобы гонять контент на них. А тему критично оставить такой же?

**Comment by IRus** [comment]
Там статьи в HTML, можно прям из собранной страницы выцепить (+ в репозитории уже есть сорцы в виде md, для них я юзаю http://markdowntohtml.com/).

https://github.com/BelarusKUG/bkug.by/blob/master/community/Meetup%208.md
https://github.com/BelarusKUG/bkug.by/blob/master/community/Meetup3.html

Ну хз, наверно можно и поменять, но эта достаточно качественная.

**Comment by IRus** [comment]
Предлагай темы в общем

**Comment by madhead** [comment]
Боюсь, конкретно эту ещё не портировали на Hugo, но есть похожие

- [Learn](https://themes.gohugo.io/theme/hugo-theme-learn/en)
- [Blackburn ](https://themes.gohugo.io/theme/blackburn/), как у https://jprof.by
- [Tranquilpeak ](https://themes.gohugo.io/theme/hugo-tranquilpeak-theme/)
- [Future Imperfect](https://themes.gohugo.io/theme/future-imperfect/)

**Comment by IRus** [comment]
Мне кажется [crisp](https://themes.gohugo.io/crisp/) больше походит на Author. Честно говоря они все мне не нравятся :)

**Comment by madhead** [comment]
Значит, надо мутить свою тему :(

**Comment by IRus** [comment]
Hyde норм выглядит

**Comment by madhead** [comment]
Ага. Чуть допилить надо, правда.

**Comment by madhead** [comment]
И под мобилки не оптимизирована :(

**Comment by IRus** [comment]
I'm implementing simple Kotlin based backend instead
