### ISSUE TITLE
Дизайн маек BKUG

### ISSUE THREAD

**Issue by IRus** [KotlinBy/bkug.by#22]
Майки для всех членов сообщества

**Comment by madhead** [comment]
1. Вывернуть все K наружу в логотипе сообществ, чтобы получился василёк
2. Взять птицу Kotlin Conf и стилизовать под аиста

**Comment by madhead** [comment]
![image](https://user-images.githubusercontent.com/577360/45764686-eff98680-bc3b-11e8-9ab8-00f03a6c3154.png)

**Comment by IRus** [comment]
https://www.google.com/search?tbm=isch&q=stork%20origami&tbs=imgo:1

**Comment by IRus** [comment]
[kotlinconf.pdf](https://github.com/BelarusKUG/bkug.by/files/2429593/kotlinconf.pdf)
